### ISSUE TITLE
MePolyInput input types

### ISSUE THREAD

**Issue by kcpevey** [Aquaveo/xmsmesh#22]
Can `xmsmesh_py.meshing.MePolyInput.outside_poly` accept inputs of any type other than tuple of tuples?

**Comment by gagelarsen** [comment]
@kcpevey can you give me an example of what you would like to do and I can investigate if we can do it?

**Comment by kcpevey** [comment]
I'd like to be able to give it shapely polygons or something like that.

**Comment by gagelarsen** [comment]
Also make a complete list of args in the constructor so that all properties could be set.

**Comment by alemon-aquaveo** [comment]
Let's make another San Diego notebook where the boundary comes from a shapefile
