### ISSUE TITLE
xmsmesh.meshing.PolyInput error in version 3.0.0

### ISSUE THREAD

**Issue by WilliamBLeonard** [Aquaveo/xmsmesh#44]
To whom it may concern:
 
I am experiencing an issue with xmsmesh 3.0.0 on my Mac. Specifically, when using the “xmsmesh.meshing.PolyInput” class, a TypeError occurs with input data. However, no such error occurs when using xmsmesh 2.0.0. I would appreciate any assistance you can provide.
 
The relevant portion of the error log is as follows:
 
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-1-186512e80e16> in <module>
     56     il_poly_segments_decon, il_unique_segments = _reorder_segments(il_poly_segments,l_catchment_polygons)
     57     il_recombined_catch = _recombine_catchments(il_poly_segments_decon,il_unique_segments)
---> 58     pts, cells = _call_XMSmesh(il_recombined_catch)
     59     o_adh_model = _build_FEM_mesh(pts,cells,'polytest')
 
~/catchment-mesher/catchment-mesher/Mesher_Mods.py in _call_XMSmesh(il_recombined_catch)
    108     for i_poly in range(0, 1):
    109 
--> 110         l_input_polygons.append(xmsmesh.meshing.PolyInput(out_poly = il_recombined_catch[i_poly]))
    111 
    112 
 
TypeError: __init__(): incompatible constructor arguments. The following argument types are supported:
    1. xmsmesh.meshing.PolyInput(outside_polygon: iterable, inside_polygons: iterable=(), bias: float=1.0, const_size_bias: object=None, const_size_fuction: object=None, bound_pts_to_remove: object=None, relaxation_method: object=None, remove_interal_four_triangle_pts: object=None, seed_points: object=None, size_function: object=None, patch_polygon_corners: iterable=(), elev_function: object=None)

**Comment by kcpevey** [comment]
@WilliamBLeonard Can you post a concise reproducible example for us to test?  
  
I'm not seeing the same behavior. There were some significant API changes between 2.0 and 3.0. For example, I'm now using this syntax:  
  
`xmsmesh.meshing.PolyInput(outside_polygon=outdata)`

**Comment by gagelarsen** [comment]
After reading through your error log it looks like Kim is correct. The key word argument you have used is ‘out_poly’ and the api change we put in to 3.0 was significant. The new keyword is ‘outside_polygon’ as shown on Kim’s example.
